### ISSUE TITLE
Return some payload metadata fields from search method

### ISSUE THREAD

**Issue by konklone** [Censys/censys-python#10]
Right now there's no way for a client that's using this library to tell how many pages are involved in a query, and to manage pagination for itself. This would be especially helpful for large queries.

The `search()` method uses an iterator to return results in a streaming fashion for as long as the caller would like. I propose either:

* a higher level method, such as `query()`, that does what `search()` does but doesn't iterate through the results, instead just returning the decoded payload (which includes metadata about pagination)
* or, another method intended to just return the metadata for a given query. The caller would understand they are incurring an HTTP request and discarding a page of results just to get the metadata.

**Comment by zakird** [comment]
fcb8db5 implements the second proposal. Let me know if this doesn't meet your needs.

**Comment by zakird** [comment]
fb3dadd implements the first. If these work, let me know, and I'll push out a new egg version.

**Comment by konklone** [comment]
Wow, thank you -- I'll integrate one or both of these now and see how it goes.

**Comment by konklone** [comment]
@zakird I used the `metadata()` method in https://github.com/18F/domain-scan/pull/85/commits/7fee68714b9e995edae9e0826e469f5b41b1bc32, and it works great. Thank you for doing this!
