### ISSUE TITLE
how to solve this error No module named 'censys.certificates' 

### ISSUE THREAD

**Issue by tatlisoft** [censys/censys-python#109]
No module named 'censys.certificates'
sys:1: RuntimeWarning: coroutine 'start.<locals>.store' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
during work with theHarvester 
censys installed and certificates has been set

**Comment by thehappydinoa** [comment]
Hi there, this is a known error for `theHarvester`. I believe it was fixed in the last major release: https://github.com/laramies/theHarvester/issues/780.
