### ISSUE TITLE
Quota Stats via API Query

### ISSUE THREAD

**Issue by rarawls** [censys/censys-python#146]
Manually keeping track of how many queries we have used is error prone and challenging with system restarts.  It would be really helpful if we could hit the API and ask for the query quota and how much we have used so that we could programmatically set our burn rate.  This would still be helpful even if it counted against our queries for the month (but it would be nice if it didn't 😄 ).  Thanks in advance!

I have found a way to make separate connection with the v1 api (but not v2) and get the quota info, but it would be nice not to have to have two separate connections for this functionality.

**Comment by thehappydinoa** [comment]
Hey there, just so you know the v1 account endpoint keeps track of quota across v1 and v2. I can absolutely make a method in the v2 base class to make sure it is easily accessible.

**Comment by rarawls** [comment]
That would be awesome as it would give us the ability to have only one version of the Censys API in our codebase.  It looks to me like there used to be methods that have been commented out in the v2 API... lines 82-100 in search/v2/api.py
https://github.com/censys/censys-python/blob/9ae7fc007df0a8b01ced11428039c0f7b8eeb43d/censys/search/v2/api.py#L82

**Comment by thehappydinoa** [comment]
Yup, that was before it was ported over, I will make an MR this afternoon, thanks for reporting this

**Comment by rarawls** [comment]
Sure thing.  Thanks very much for the quick response and help.
