### ISSUE TITLE
Unable to use Censys CLI

### ISSUE THREAD

**Issue by kaze-nomamani** [censys/censys-python#151]
I copied & pasted cli command from documentation at https://censys-python.readthedocs.io/en/stable/usage-cli.html.

I can not use censys cli because I got errors if I tried to search hosts. When I tried to search ipv4, I will get empty response... How can I get data from censys API?

---------------------------

CLI command

censys search 'services.http.response.html_title: "Tesla Energy Powerpack"' --index-type hosts

----------------------------

Error message

censys search: error: argument --index-type: invalid choice: 'hosts' (choose from 'ipv4', 'certs', 'websites')

------------------------------

**Comment by kaze-nomamani** [comment]
I upgraded censys via pip command. My version is 2.0.6

--------------------------------

pip install --upgrade censys

-------------------

**Comment by thehappydinoa** [comment]
Hi there, would you be able to run `censys --version`? There sounds like there maybe some version mixmatch.

**Comment by thehappydinoa** [comment]
Hi @kaze-nomamani just following up. Here is the output of the following commands.

```sh
$ censys search --index-type hosts
usage: censys search [-h] [--api-id API_ID] [--api-secret API_SECRET] [--index-type ipv4|certs|websites|hosts] [-f screen|json|csv] [-o OUTPUT] [--open] [--fields FIELDS [FIELDS ...]] [--overwrite] [--max-records MAX_RECORDS] [--pages PAGES] query
censys search: error: the following arguments are required: query
```
This is expected as I did not provide a query.

```sh
$ censys --version
Censys Python Version: 2.0.6
```
I am on the most recent release.

```sh
$ censys search 'services.http.response.html_title: "Tesla Energy Powerpack"' --index-type hosts
[]
```
This is to be expected as there are no longer any [search results from that query](https://search.censys.io/search?resource=hosts&q=services.http.response.html_title%3A+%22Tesla+Energy+Powerpack%22). 

I would try checking your Python PATH and checking the installation location of the `censys` command.

```sh
$ which censys
```

If there is anything else I can do to help please let me know.

**Comment by kaze-nomamani** [comment]
Resolved when I used newly created kali vm & venv. Thank you for reply.
