### ISSUE TITLE
Quota call doesn't use proxy settings

### ISSUE THREAD

**Issue by mitsuo0114** [censys/censys-python#155]
**Describe the bug**
When we call `CensysHost.quota()` in censys.search, ignores proxy settings which was specified in CensysHosts constructor.

**To Reproduce**

1. Install 2.0.6 and run following code. 
(Which have valid api_id, api_secret and proxy settings)
```
from censys.search import CensysHosts
client = CensysHosts(api_id="XXXXXXX", api_secret="XXXXXXXX", proxies={"https":"http://<proxy_ip>:<proxy_port>"})
print(client.quota())
```

2. Then confirm actual TCP access destination.
```
$ netstat -p | grep 65247
tcp        0      1 <running server>:48232 104.26.10.245:https     SYN_SENT    65247/python 
```

**Expected behavior**
https access should head to our proxy, not 104.26.10.245.

This ip is search.censys.io.
```
$ nslookup search.censys.io
Name:   search.censys.io
Address: 104.26.11.245
```

**Device (please complete the following information):**
 - OS [e.g. Cent OS]: Cent OS
 - Censys Python Version [e.g. 1.1.0]: 2.0.6
 - Shell [e.g. bash, zsh]: bash

**Additional context**

To compare, following code which calls "view" function works as expected. 
$ python test2.py 
```
from censys.search import CensysHosts
client = CensysHosts(api_id="XXXXXXX", api_secret="XXXXXXXX", proxies={"https":"http://<proxy_ip>:<proxy_port>"})
print(client.view("104.26.11.245"))
```

```
{'ip': '104.26.11.245', 'services': [{'_decoded': 'http', '_encoding': {'banner': 'DISPLAY_UTF8', 'banner_hex': 'DISPLAY_HEX'}, 'banner': 'HTTP/1.1 403 Forbidden\nVary: Accept-Encoding\nCf-Ray: 6868f5302a3e2986-ORD\nServer: cloudflare\nX-Frame-Options: SAMEORIGIN\nExpires: Thu, 01 Jan 1970 00:00:01 GMT\nConnection:....
```

**Comment by mitsuo0114** [comment]
I guess this line ignores given **kwargs?
https://github.com/censys/censys-python/blob/main/censys/search/v2/api.py#L91

**Comment by thehappydinoa** [comment]
> I guess this line ignores given **kwargs?
> 
> https://github.com/censys/censys-python/blob/main/censys/search/v2/api.py#L91
> 
> 

This is exactly the issue, I can get a fix up today.

**Comment by thehappydinoa** [comment]
Hi @mitsuo0114, I have just released a new beta release. Please install using `pip install censys==2.0.7b1`.

**Comment by mitsuo0114** [comment]
great! thank you for really quick fix!

**Comment by thehappydinoa** [comment]
> great! thank you for really quick fix!

Absolutely, please let me know if you ever are experienced any bugs or have any ideas! There is always room for improvement.
