### ISSUE TITLE
censys.common.exceptions.CensysRateLimitExceededException: 429 (Too Many Requests): You have used your full quota for this billing period.

### ISSUE THREAD

**Issue by riramar** [censys/censys-python#163]
**Describe the bug**
I'm assuming the free account can perform "Limited queries* per month" and "Up to 1,000 results* per query" but for new fresh free account and censys CLI installation I'm getting the error below.
```
ricardo@zion:~$ censys view 8.8.8.8
Traceback (most recent call last):
  File "/home/ricardo/.local/bin/censys", line 8, in <module>
    sys.exit(main())
  File "/home/ricardo/.local/lib/python3.9/site-packages/censys/cli/__init__.py", line 21, in main
    args.func(args)
  File "/home/ricardo/.local/lib/python3.9/site-packages/censys/cli/commands/view.py", line 44, in cli_view
    document = index.view(args.document_id, **view_args)
  File "/home/ricardo/.local/lib/python3.9/site-packages/censys/search/v2/api.py", line 262, in view
    return self._get(self.view_path + document_id, args)["result"]
  File "/home/ricardo/.local/lib/python3.9/site-packages/censys/common/base.py", line 213, in _get
    return self._make_call(self._session.get, endpoint, args)
  File "/home/ricardo/.local/lib/python3.9/site-packages/censys/common/base.py", line 41, in _wrapper
    return _impl()
  File "/home/ricardo/.local/lib/python3.9/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/home/ricardo/.local/lib/python3.9/site-packages/censys/common/base.py", line 39, in _impl
    return method(self, *args, *kwargs)
  File "/home/ricardo/.local/lib/python3.9/site-packages/censys/common/base.py", line 203, in _make_call
    raise censys_exception(
censys.common.exceptions.CensysRateLimitExceededException: 429 (Too Many Requests): You have used your full quota for this billing period. Please see https://censys.io/account/billing or contact support@censys.io.
ricardo@zion:~$ censys --version
Censys Python Version: 2.0.7
ricardo@zion:~$ 
```

**To Reproduce**
1. Create a new free account
2. Install censys CLI
3. Run "censys view 8.8.8.8"

**Expected behavior**
Get the results.

**Device (please complete the following information):**
 - OS [e.g. macOS]: Kali
 - Censys Python Version [e.g. 1.1.0]: 2.0.7
 - Shell [e.g. bash, zsh]: Bash

**Additional context**

**Comment by thehappydinoa** [comment]
Hi there @riramar,

I am currently unable to replicate this issue. Did you remember to run `censys config` and update your credentials? The only thing I can think of is the potential use of old credentials.

**Comment by riramar** [comment]
Hi @thehappydinoa 

Thanks for the quick reply. Yes, I did `censys config` before and as you can see below the API creds are in the config file.

```
ricardo@zion:~$ cat .config/censys/censys.cfg 
[DEFAULT]
api_id = XXXXXXXXXX
api_secret = XXXXXXXXXXX
asm_api_key = 

ricardo@zion:~$ 

```

**Comment by thehappydinoa** [comment]
@riramar What happens if you attempt to run this chunk of python?

```python
from censys.search import CensysHosts
h = CensysHosts()
print(h.quota())
```
This should return your current quota allowance. Below is from my newly created community account.
```json
{"used": 2, "allowance": 250, "resets_at": "2021-10-1 12:00:00"}
```

**Comment by riramar** [comment]
I got the problem now. Sorry for my mistake.
I was setting as OS system variable old API keys though my .bashrc file.
So even that I set new API keys using the CLI `censys config` (.config/censys/censys.cfg) during the search the censys command was using the OS variable instead of the ones stored on .config/censys/censys.cfg which make sense to me.
I'm really sorry for the confusion. That's totally on me. :(

**Comment by thehappydinoa** [comment]
@riramar No worries at all, I am glad you figured it out. Please let me know if you run into any other issues or have any ideas to make this library even better!

**Comment by riramar** [comment]
I'll try to send a PR in order to check the OS variables after running the command `censys config`.
It could send a warning to the user saying the OS variable will be used instead of the config file.

**Comment by thehappydinoa** [comment]
That would be a really good idea, I may be able to include it in my PR.

**Comment by riramar** [comment]
I believe warning check should start here https://github.com/censys/censys-python/blob/main/censys/cli/commands/config.py#L52.
Please let me know if you'll do that otherwise I can send a PR.
