### ISSUE TITLE
New variables for Host Risk in LogBook API

### ISSUE THREAD

**Issue by snowgears** [censys/censys-python#197]
It appears the current logbook has new variables for host risk.

If these were accessible that would be great!

![Screen Shot 2021-11-16 at 12 25 41 PM](https://user-images.githubusercontent.com/4141199/142044815-59285620-b51a-4437-a24f-8be4d330a08e.png)

**Comment by thehappydinoa** [comment]
I believe this can now be accomplished using the Risks v2 API. I am going to go ahead and close this.
