### ISSUE TITLE
Account Usage Percentage showing decimal and percent sign.

### ISSUE THREAD

**Issue by drb-ra** [censys/censys-python#211]
**Describe the bug**

CLI account command is show quota as decimal but including a percent sign too.. so it's shows 0.70% instead of 0.70 or 70%.

**To Reproduce**
Execute: censys account

**Expected behavior**

**Device (please complete the following information):**
 - OS [e.g. macOS]: Linux
 - Censys Python Version: 2.1.0
 - Shell [e.g. bash, zsh]: bash

**Comment by thehappydinoa** [comment]
Hi @drb-ra, I have just fixed this in cb1e3269c1a66a169c4b7d8e50e7ca1705179f36. It will be included in the next release.
