### ISSUE TITLE
Virtual Host Search CLI

### ISSUE THREAD

**Issue by thehappydinoa** [censys/censys-python#217]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would want a optional cli argument to be able to interact with virtual hosts.

**Comment by mimu-pl** [comment]
it will be great to included this feat in next update! the pip installation of censys modules not having this

**Comment by thehappydinoa** [comment]
@mimu-pl It will be available in our upcoming 2.1.1 release. Thanks for the interest!

**Comment by thehappydinoa** [comment]
Hi @mimu-pl,

We have now released version 2.1.1. Upgrade with `pip install --upgrade censys`.

**Comment by mimu-pl** [comment]
Hi @thehappydinoa thank you for letting me know,
just got the update...
