### ISSUE TITLE
[!] Error: 422 (Unprocessable Entity): Invalid search. Your query could not be parsed

### ISSUE THREAD

**Issue by AhrimanSefid** [censys/censys-python#225]
Censys:
{'used': 0, 'allowance': 250, 'resets_at': '2022-02-04 17:10:03'}
[!] Error: 422 (Unprocessable Entity): Invalid search. Your query could not be parsed

https://github.com/f4rber/BruteMiner

**Comment by thehappydinoa** [comment]
Hi there, that project appears to be using an out-of-date query: `80.http.get.body: Awesome Miner` we have since updated our [Search Query Language](https://search.censys.io/search/language?resource=hosts) and the new query that can search across all ports would look like this:

```
services.http.response.body: "Awesome Miner"
```
> [Search Results](https://search.censys.io/search?resource=hosts&q=services.http.response.body%3A+%22Awesome+Miner%22)

**Comment by thehappydinoa** [comment]
As I have made a branch that fixes that issue here: [thehappydinoa/BruteMiner:update-censys-queries](https://github.com/thehappydinoa/BruteMiner/tree/update-censys-queries) I am going to go ahead and close this issue. Thanks for reporting.
