### ISSUE TITLE
Specify Config File Location

### ISSUE THREAD

**Issue by jheadings** [censys/censys-python#238]
Is there a way to configure the api to write the config file to a specific location. This causes issues in environments where the root is not writable.

**Comment by thehappydinoa** [comment]
Hey there, this is a great idea. I will happily change this to a feature request.

As an alternative option you can always set the following environmental variables: `CENSYS_API_ID` and `CENSYS_API_SECRET`.

**Comment by TBbeau** [comment]
@thehappydinoa - thank you for the extremely quick reply.

It looks like `__init__` will search for a config file regardless of whether or not the env vars are supplied, is that correct?

**Comment by thehappydinoa** [comment]
@TBbeau Happy to help. But that is correct, I am modifying it now to accept a new path. I am considering a new env var: `CENSYS_CONFIG` that when set overwrites `~/.config/censys/censys.cfg`, would this work for your environment?

**Comment by thehappydinoa** [comment]
Hi @jheadings and @TBbeau,

We have just released version [`2.1.2`](https://github.com/censys/censys-python/releases/tag/v2.1.2) that provides additional configuration options as well as disabling the default write config behavior. This should fix any issues in environments without a writeable root.
