### ISSUE TITLE
ImportError: cannot import name IPv4

### ISSUE THREAD

**Issue by ReverseBrain** [censys/censys-python#24]
I'm trying to write a Python script but when I try to import the censys package and run the script I got the following error:
`ImportError: cannot import name IPv4`
The script is really simple:
`import sys`
`import json`
`import requests`
`import socket`
`import censys`
`c = censys.ipv4.CensysIPv4(api_id="XXX", api_secret="XXX")`
`print c.search("ETH")`

**Comment by zakird** [comment]
You need to import that module: `import censys.ipv4`.

**Comment by cdzombak** [comment]
@ReverseBrain If we have this error published in example code somewhere, please let us know and we'll fix it up.

**Comment by ReverseBrain** [comment]
The problem persists after using `import censys.ipv4`
