### ISSUE TITLE
censys search 

### ISSUE THREAD

**Issue by AhrimanSefid** [censys/censys-python#248]
hi Admin
me try code but not show port and not save txt or other file.
code:
censys search 'services.http.request.uri: /test' --index-type hosts | jq -c '.[] | {ip: .ip, port: .port}'
report site:
Hosts
Results: 340 Time: 0.54s

python try :
99
can help me fixed.

**Comment by thehappydinoa** [comment]
Hi there,

So I just tested your query and the `censys search` command and ensured it was a proper response. So I looked closer at your `jq` statement and the issue is how you are accessing the port. A host search "hit" is structured like this: 

```json
[
  {
    "ip": "8.8.8.8",
    "services": [
      {
        "port": 53,
        "service_name": "DNS",
        "transport_protocol": "UDP"
      },
      {
        "port": 80,
        "service_name": "HTTP",
        "transport_protocol": "TCP"
      },
      {
        "port": 443,
        "service_name": "HTTP",
        "certificate": "3090d39a841b99d6697b9210795994cf3e9a7cc7273ab8b8fe2e875942f95002",
        "transport_protocol": "TCP"
      }
    ],
    "location": {
      "continent": "North America",
      "country": "United States",
      "country_code": "US",
      "timezone": "America/Chicago",
      "coordinates": {
        "latitude": 37.751,
        "longitude": -97.822
      },
      "registered_country": "United States",
      "registered_country_code": "US"
    },
    "autonomous_system": {
      "asn": 15169,
      "description": "GOOGLE",
      "bgp_prefix": "8.8.8.0/24",
      "name": "GOOGLE",
      "country_code": "US"
    },
    "last_updated_at": "2022-02-02T12:39:54.465Z"
  }
]
```
> For more details check out the Search API docs [here](https://search.censys.io/api#/hosts/searchHosts).

Each host has a list of services each of which contains a port. I used this `jq` command to get each port and put it into a `ports` list:

```sh
$ censys search "ip:8.8.8.8" | jq -c '.[] | {ip: .ip, ports: [.services[].port]}'
{"ip":"8.8.8.8","ports":[53,443,443]}
```
> You can find a good cheatsheet for `jq` [here](https://lzone.de/cheat-sheet/jq).

I hope this helped!

**Comment by AhrimanSefid** [comment]
I have 2 problems now, the port and the api aren't same. The api list which site gave is for example 99 but when I search the site the output list is 349. I want to save it in a text. I didn't see the output in the sheet.

**Comment by thehappydinoa** [comment]
@AhrimanSefid I am not sure I know what you mean by API list. Would you be able to show me an example of what you are referring to?

Thanks!

**Comment by AhrimanSefid** [comment]
![image](https://user-images.githubusercontent.com/1332246/152422068-6258bb17-fa1b-44e2-8a89-8c3142a4a656.png)

**Comment by thehappydinoa** [comment]
@AhrimanSefid The Search command by default returns 100 results per page. If you pass in `--pages=-1` it will retrieve all pages. We have it set to return only 1 page unless otherwise specified.

**Comment by AhrimanSefid** [comment]
thanks try,
but need save txt or export data.

**Comment by AhrimanSefid** [comment]
![image](https://user-images.githubusercontent.com/1332246/152430170-865681e2-5966-41ce-ab2b-cb4f70793126.png)

**Comment by thehappydinoa** [comment]
> ![image](https://user-images.githubusercontent.com/1332246/152430170-865681e2-5966-41ce-ab2b-cb4f70793126.png)
> 
> 

The `--pages=-1` goes after your search query like in the following: `censys search "query here" --pages=-1`

**Comment by AhrimanSefid** [comment]
worked and thank you.
but 1 q : export or save list ip,port.

**Comment by thehappydinoa** [comment]
You should be able to pipe (`>`) it into a file. `censys search ... | jq ... > hosts.jsonl`

**Comment by AhrimanSefid** [comment]
can export line?

![image](https://user-images.githubusercontent.com/1332246/152495644-227e4cd8-c7a2-4d80-919e-ea581989d3cc.png)
