### ISSUE TITLE
ImportError: No module named certificates

### ISSUE THREAD

**Issue by Swiffers** [censys/censys-python#25]
1. `pip install censys`
2. `import censys.certificates`

--> `ImportError: No module named certificates`

Python 2.7 on OSX 10.13.4

**Comment by nafuti** [comment]
I had this problem too but after abit of examination, i realised my pip was installing to the python3 dist-package folder yet my python referenced python 2.7. i just executed the script with python3 and it was solved.

**Comment by droope** [comment]
I had the a similar issue. It is because I named my file `censys.py`. If you change the name to something else, such as `censys_getwhatever.py` this will resolve the issue, provided you also delete any temporary `pyc` files.

**Comment by thehappydinoa** [comment]
Hi,

This issue appears to have been solved so I am closing it.

**Comment by wowits** [comment]
I am facing this issue
python censys_subdomain_finder.py instagram.com 

Traceback (most recent call last):
  File "censys_subdomain_finder.py", line 3, in <module>
    import censys.certificates
ImportError: No module named censys.certificates



python3 censys_subdomain_finder.py instagram.com 
/home/fince/h1tools/tools/censys-subdomain-finder/censys_subdomain_finder.py:41: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(subdomains) is 0:
/home/fince/h1tools/tools/censys-subdomain-finder/censys_subdomain_finder.py:53: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if output_file is None or len(subdomains) is 0:
Traceback (most recent call last):
  File "/home/fince/h1tools/tools/censys-subdomain-finder/censys_subdomain_finder.py", line 3, in <module>
    import censys.certificates
ModuleNotFoundError: No module named 'censys.certificates'




![prob](https://user-images.githubusercontent.com/82223747/126678293-6c639679-d903-48bd-b13d-778b62b9c506.png)

**Comment by thehappydinoa** [comment]
Hi @wowits,

The `censys-subdomain-finder` tool is not an official tool and appears to not be maintained. I have created [a PR for the project](https://github.com/christophetd/censys-subdomain-finder/pull/12), but it has not been accepted. You are more than welcome to use my branch: [`thehappydinoa/censys-subdomain-finder:censys-update`](https://github.com/thehappydinoa/censys-subdomain-finder/tree/censys-update).

They are using an old version of `censys-python`, to install a legacy version please run:

```sh
pip install "censys==2.0.0; python_version > '3.6'" "censys==0.0.8; python_version <= '3.6'"
```

**Comment by joao-wivo** [comment]
Solved my problem with python3 

sudo pip3 install "censys==2.0.7; python_version > '3.8'" "censys==0.0.8; python_version <= '3.8'"

**Comment by thehappydinoa** [comment]
Thank you @joao-wivo I have updated my answer above.

**Comment by Done461** [comment]
> Solved my problem with python3
> 
> `sudo pip3 install "censys==2.0.7; python_version > '3.8'" "censys==0.0.8; python_version <= '3.8'"`

solved my issue thanks :D
