### ISSUE TITLE
{Bug}

### ISSUE THREAD

**Issue by AhrimanSefid** [censys/censys-python#254]
Hi.
Why?
Hosts
Results: 872 Time: 0.00s

![image](https://user-images.githubusercontent.com/1332246/153717630-57af8a45-4e9d-4ad1-bfd1-a88d4186af52.png)

**Comment by thehappydinoa** [comment]
Hi @AhrimanSefid,

Thank you for reporting this. I have passed these details to the appropriate team.

**Comment by thehappydinoa** [comment]
Just following up, this issue has been fixed.
