### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by AhrimanSefid** [censys/censys-python#263]
Hi 
page 1
![image](https://user-images.githubusercontent.com/1332246/155695547-2c9dcd08-a49d-497e-81d9-dce81717ea05.png)

Click Next Page:

![image](https://user-images.githubusercontent.com/1332246/155695818-6e2104e9-7a49-477b-bd2e-2d139abd8073.png)

**Comment by thehappydinoa** [comment]
Hi there,

Thank you for reporting this issue. I have notified the team and they are working to resolve it. I will keep this ticket updated as I learn more.

**Comment by thehappydinoa** [comment]
@AhrimanSefid I believe that this issue with full text searches has been resolved. I am going to go ahead and close this issue, but please feel free to reopen if you are still having difficulties with that query.
