### ISSUE TITLE
Upgrade the Python version of dependency importlib-metadata to latest version (3.10)

### ISSUE THREAD

**Issue by FantasqueX** [censys/censys-python#273]
Hi there! I would like make a ArchLinux package of python-censys. However I find `importlib-metadata = { version = "*", python = "<3.8" }` which means python-censys should be install with Python version < 3.8. ArchLinux only keeps the latest version software. So I would like to know what blocks you to upgrade the version Python installed with importlib-metadata. If there is anything I can do, I will offer help happily.

**Comment by FantasqueX** [comment]
This is the first time I have encountered poetry, and it seems that I misunderstand with the document. Thanks for answering and sorry for inconvenience I caused.

**Comment by thehappydinoa** [comment]
@FantasqueX No worries at all, I am happy that we have documented the answer for future users who might be curious. 

If you have any other questions about `poetry` or our setup I would be glad to answer them either here or under the discussions tab.
