### ISSUE TITLE
how can i export the results my query to a CSV ?

### ISSUE THREAD

**Issue by minanagehsalalma** [censys/censys-python#29]

**Comment by thehappydinoa** [comment]
Hi, at the moment we don't have built-in functionality to write to CSV. However, by using the [`csv`](https://docs.python.org/3/library/csv.html) library you are able to write specific values to a CSV file. Here is an example of this: [thehappydinoa/Censys-Certificates](https://github.com/thehappydinoa/Censys-Certificates)

**Comment by minanagehsalalma** [comment]
> Hi, at the moment we don't have built-in functionality to write to CSV. However, by using the [`csv`](https://docs.python.org/3/library/csv.html) library you are able to write specific values to a CSV file. Here is an example of this: [thehappydinoa/Censys-Certificates](https://github.com/thehappydinoa/Censys-Certificates)

ok thanks

**Comment by thehappydinoa** [comment]
I am currently making a PR to add a CLI. One of the features is writing to CSV and JSON. You can check it out at #42

**Comment by minanagehsalalma** [comment]
@thehappydinoa sorry for the late answer ... how do i grab it or use it ?

**Comment by thehappydinoa** [comment]
Hi @minanagehsalalma,

We recently merged the CLI into the main library. To update run:

```sh
$ pip install --upgrade censys
```

Then you want to checkout the [CLI Format Docs](https://censys-python.readthedocs.io/en/latest/cli.html#cmdoption-censys-search-f) which specifies the output of the search query. 

Please let me know if you have anymore questions.
