### ISSUE TITLE
Allow backoff 2.x

### ISSUE THREAD

**Issue by utkonos** [censys/censys-python#293]
**Is your feature request related to a problem? Please describe.**

There is a dependency lock on `backoff` via a Poetry carot requirement. So far there has been no problems that I have observed using the new 2.x branch of `backoff`. The changes to `backoff` that warranted a major version change appear to be adding and dropping Python version support rather than API changes according to their release notes here:

https://github.com/litl/backoff/releases

**Describe the solution you'd like**

Change the `backoff` carot requirement from the following:

https://github.com/censys/censys-python/blob/7e2faa4424d9345ae597711615152eeff2770ff6/pyproject.toml#L56

To:

```
backoff = "^2.0.1"
```

**Additional context**

Doing a bit of blame research, the following change is the one which locked `backoff` to the major version via carot requirement:

https://github.com/censys/censys-python/blame/7e2faa4424d9345ae597711615152eeff2770ff6/pyproject.toml#L56

This is the commit which made this change along with a number of others:

https://github.com/censys/censys-python/commit/b9dea610ad33a5babe629d979bc6727783da86d8

Here is the only location in the code base that uses `backoff`:

https://github.com/censys/censys-python/blob/8294fef8ace357316f6c69e3447d8cc950427dbe/censys/common/base.py#L21-L39

Dependency resolver error in pip:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
censys 2.1.3 requires backoff<2.0.0,>=1.11.1, but you have backoff 2.0.1 which is incompatible.
```

**Comment by thehappydinoa** [comment]
Hi @utkonos,

Unfortunately we would like to continue to support 3.6. I would however be okay with setting the version to `>=1.11.1` if that would solve your specific issue.

**Comment by utkonos** [comment]
@thehappydinoa Yes, that would solve the specific issue. I adjusted my PR. Thanks for being quick on the draw!

**Comment by utkonos** [comment]
Slightly off topic, but Python 3.6 no longer recieves security fixes. Using it requires accepting and understanding the risks involved. However, I understand business motivation to support clients who remain on unsupported versions.

**Comment by thehappydinoa** [comment]
@utkonos That is definitely a good point, it may be worth while dropping support in the near future. Thank you for the quick PR, your contribution is greatly appreciated. I will look into our needs on the Python 3.6 front.
