### ISSUE TITLE
Results from historical view return `CensysNotFoundException`

### ISSUE THREAD

**Issue by andharris** [censys/censys-python#38]
I'm attempting to pull historical results from the domains dataset.

```python
from censys.data import CensysData

series = 'domain_2018'
censys = CensysData()
series_view = censys.view_series(series)
series_results = censys.view_result(series, '20190812')
...
CensysNotFoundException: 404 (unknown): The requested page does not exist.

# however when I look for '20190812' within the historical results I find a record that makes me think it should exist
[record for record in series_view['results']['historical'] if record['id'] == '20190812']

[{'timestamp': '20190813T034051',
  'id': '20190812',
  'details_url': 'https://www.censys.io/api/v1/data/domain_2018/20190812'}]
```

Is there a reason the historical results would include details URLs that don't exist?

**Comment by thehappydinoa** [comment]
hi @andharris I just wanted to follow up on this issue. Are you still experiencing this issue? If so there is a new release, give it a try and let me know how it goes.

**Comment by andharris** [comment]
hi, yes I am still having this issue. I'll try the latest release.

**Comment by thehappydinoa** [comment]
@andharris Did upgrading solve your problem? If so can I close this issue?

**Comment by andharris** [comment]
Sorry for the delayed response. This appears to be resolved now. Thanks.
