### ISSUE TITLE
[Question] only save port services

### ISSUE THREAD

**Issue by lolminerxmrig** [censys/censys-python#387]
Hi,

I tried this line

```bash
censys search 'services.http.request.uri="*/carbon/admin/login.jsp"' --pages=-1 | jq -c > 1.txt '.[] | {ip: .ip, ports: [.services[].port]}'
```

report on all ports:

```json
{"ip":"*.*.*.*","ports":[22,5432,8000,8081,8082,8083,8084,8085,8086,8087,8089,9000,9090,9443,9444]}
```

I need to only save port services

**Comment by thehappydinoa** [comment]
Hi @lolminerxmrig,

I think you are looking for both the service name and the port. To do that you can change your `jq` command to

```bash
censys search ... | jq -c '.[] | {ip: .ip, ports: [.services[].port], service_names: [.services[].service_name]}' > results.json 
```

For now I am going to go ahead and close this issue, but I am more than happy to continue this as a GitHub discussion.

**Comment by lolminerxmrig** [comment]
![image](https://user-images.githubusercontent.com/108659226/196058216-2c8022da-20d3-4abf-b1f1-4640b45c2e55.png)

**Comment by lolminerxmrig** [comment]
![image](https://user-images.githubusercontent.com/108659226/196058292-1fc51a3d-14fb-4802-afc6-92f03c5765a7.png)

**Comment by lolminerxmrig** [comment]
Save only the active port for search, not all.

![image](https://user-images.githubusercontent.com/108659226/196058387-379bb3cf-c5d4-4a3b-84ab-fdfe48a48bca.png)
