### ISSUE TITLE
{Bug Show}

### ISSUE THREAD

**Issue by lolminerxmrig** [censys/censys-python#392]
Hi
Why ?
Results: Aborted

![image](https://user-images.githubusercontent.com/108659226/198320181-d4c99cae-7751-4f8f-a01e-4f33fe779cbc.png)

Next Page :

![image](https://user-images.githubusercontent.com/108659226/198320570-4698fd5b-e5bf-40ff-96af-2a0ea28eaaf3.png)

**Comment by thehappydinoa** [comment]
You may get better results searching on a specific field, string matching across all fields historically can take some time.

I did however alert the team and they will look into any timeouts you may have encountered.

**Comment by lolminerxmrig** [comment]
I tried everything.
But the problem was not solved.
but you can help for fixed?

**Comment by thehappydinoa** [comment]
Hi @lolminerxmrig,

I believe the issue was fixed, but if the query actually times out, it may be best to write the query for a more narrow set of parameters.

**Comment by lolminerxmrig** [comment]
ok.try.
thanks a lot.
