### ISSUE TITLE
Censys Metadata issue

### ISSUE THREAD

**Issue by papichamonz** [censys/censys-python#447]
im trying to use the metadata function of censys but on the output tells me:

"meta = h.metadata(ip)  # pass the IP address as an argument here

TypeError: metadata() takes 1 positional argument but 2 were given"

can someone help me?

`from censys.search import CensysHosts

h = CensysHosts()

ip = input("Insert an IP: ")

host = h.view(ip) #working
print("-" * 30)
print("DATA DISCOVERED:")
print(host)

meta = h.metadata(ip)  # not working
print("-" * 30)
print("SERVICES DISCOVERED:")
print(meta)

names = h.view_host_names(ip) #working 
print("-" * 30)
print("HOSTNAMES DISCOVERED:")
print(names)
`

**Comment by thehappydinoa** [comment]
Hey there, metadata can be called like this: `client.metadata()` it takes in no parameters and returns data about the entire index of hosts.

**Comment by papichamonz** [comment]
I already tried it and it shows me a  complete list of services and i presume this is the wrong output, because in theory it shouldnt give that many services like bitcoin or terraria...
the output is this one
**" {'services': ['AMQP', 'ANDROMOUSE', 'ANYCONNECT', 'ARD', 'ATG', 'BACNET', 'BEANSTALKD', 'BGP', 'BITCOIN', 'BITTORRENT', 'BITTORRENT_TRACKER', 'BOLT', 'CASSANDRA', 'CHARGEN', 'CITRIX', 'COAP', 'CODESYS', 'CWMP', 'DB2', 'DICT', 'DIGI', 'DNP3', 'DNS', 'EIP', 'ELASTICSEARCH', 'FINS', 'FORTIGATE', 'FORTIGUARD', 'FOX', 'FTP', 'GE_SRTP', 'HART', 'HTTP', 'ICAP', 'IDENT', 'IEC60870_5_104', 'IKE', 'IMAP', 'IPMI', 'IPP', 'IRC', 'KAFKA', 'KERBEROS', 'KUBERNETES', 'LDAP', 'MDNS', 'MEMCACHED', 'MIKROTIK_BW', 'MMS', 'MODBUS', 'MONGODB', 'MQTT', 'MSSQL', 'MURMUR', 'MYSQL', 'NATPMP', 'NETBIOS', 'NETIS', 'NTP', 'OPENVPN', 'ORACLE', 'PCWORX', 'PC_ANYWHERE', 'PIGEONHOLE', 'PJL', 'POP3', 'POPPASSD', 'PORTMAP', 'POSTGRES', 'PPTP', 'PROMETHEUS', 'PRO_CON_OS', 'QOTD', 'RADIUS', 'RDP', 'REDIS', 'RETHINKDB', 'RIPV1', 'RSYNC', 'RTSP', 'S7', 'SCCM', 'SENTINEL', 'SIP', 'SKINNY', 'SLP', 'SMB', 'SMTP', 'SNMP', 'SSDP', 'SSH', 'STATSD', 'TEAMSPEAK', 'TEAM_VIEWER', 'TELNET', 'TERRARIA', 'TFTP', 'TORCONTROL', 'UBIQUITI', 'UNKNOWN', 'UPNP', 'VALVE', 'VNC', 'WDBRPC', 'WS_DISCOVERY', 'X11', 'XDMCP', 'XMPP', 'ZOOKEEPER']}
------------------------------"**

**Comment by thehappydinoa** [comment]
@papichamonz That is actually the purpose of the metadata endpoint. It has nothing to do with a specific host, domain, or ip address. It provides general information about the services Censys scans. Hope this helps, if you have more questions I would suggest checking out the [API docs for Censys Search](https://search.censys.io/api).
