### ISSUE TITLE
{search}

### ISSUE THREAD

**Issue by lolminerxmrig** [censys/censys-python#448]
search :
(services.software.uniform_resource_identifier="cpe:2.3:a:jupyter:notebook:\*:\*:\*:\*:\*:\*:\*:\*" and services.http.request.uri="/lab/") and services.http.response.status_code="200"

![image](https://user-images.githubusercontent.com/108659226/221985030-b9030a5c-a05a-4f40-ab8a-78cda532358d.png)

**Comment by thehappydinoa** [comment]
Hi @lolminerxmrig,

This issue appears to be related to our search engine and not specifically our Python library. I would suggest reaching out to our support team for better equipped support on our Search DSL. Their email is [support@censys.io](mailto:support@censys.io), I am going to close this issue.
