### ISSUE TITLE
when want useing censys.certificates  error 

### ISSUE THREAD

**Issue by Ibrahem4** [censys/censys-python#46]
Traceback (most recent call last):
  File "censys_subdomain_finder.py", line 3, in <module>
    import censys.certificates
ImportError: No module named censys.certificates

**Comment by thehappydinoa** [comment]
Hi,

As shown [here](https://github.com/censys/censys-python/issues/37#issuecomment-679176751) this should work. Would you be able to provide the output of 

```bash
pip show censys 
```

**Comment by Ibrahem4** [comment]
hey my friend  how are you ihope your are fine  this resualt its come after  write command 
Name: censys
Version: 1.0.0
Summary: An easy-to-use and lightweight API wrapper for the Censys Search Engine (censys.io).
Home-page: https://github.com/censys/censys-python
Author: Censys Team
Author-email: support@censys.io
License: Apache License, Version 2.0
Location: /home/virus/.local/lib/python3.8/site-packages
Requires: requests
Required-by:

**Comment by Ibrahem4** [comment]
thanks man i show pip install module in python 3.8 and defualt python is 2.7 and i change my alternative python to 3.8 and its work

**Comment by thehappydinoa** [comment]
@Ibrahem4 perfect. Since that solved it, I am going to close this issue. Reach out if the problem persists.
