### ISSUE TITLE
422 Error running censys subdomains

### ISSUE THREAD

**Issue by blackpoplar** [censys/censys-python#475]
Hi there,

looks like I'm getting an error from censys with a subdomains request. Censys appears to be working in other respects.

(.venv) PS C:\Users\xxx\censys> censys account
┌─────────────────┬────────────────────────┐
│ Email           │xxx@xxx │
│ Login ID        │ xxx@xxx │
│ First Login     │ None                   │
│ Last Login      │                        │
│ Query Quota     │ 16 / 250 (6.40%)       │
│ Quota Resets At │ 2023-05-28 10:36:50    │
└─────────────────┴────────────────────────┘
(.venv) PS C:\Users\xxx\censys> censys subdomains censys.io
422 (Unprocessable Entity): argument of type 'NoneType' is not iterable
(.venv) PS C:\Users\xxx\censys> censys -v
Censys Python Version: 2.2.0
(.venv) PS C:\Users\xxx\censys> python --version
Python 3.11.3

**Comment by thehappydinoa** [comment]
Hey there, looking into this now, thanks for bringing it to my attention.
