### ISSUE TITLE
Error 422 using fields-argument on search (v2)

### ISSUE THREAD

**Issue by Lem** [censys/censys-python#487]
**Describe the bug**
With the code below I've received
`censys.common.exceptions.CensysSearchException: 422 (Unprocessable Entity): argument of type 'NoneType' is not iterable`

**To Reproduce**
```
    censys = CensysCerts()
    query = censys.search(f"(names: `example.com`)",
                          fields=[
                              "names",
                              "fingerprint_sha256",
                              "parsed.issuer.organization",
                              "parsed.subject.postal_code",
                          ],
                          per_page=20)
```
By removing the `fields`-argument the query works fine.

**Expected behavior**
Would expect a valid json response with specified fields.

**Device (please complete the following information):**

- OS [e.g. debian, macOS]: Arch Linux
- Censys Python Version [e.g. 2.2.1]: 2.2.2
- Shell [e.g. bash, zsh]: Don't know, running from PyCharm

**Additional context**

**Comment by thehappydinoa** [comment]
I am going to go ahead and close this issue, but please let me know if you are still running into issues.
