### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lolminerxmrig** [censys/censys-python#488]
Hi.

me today test code but send me Error :
censys search "services.http.response.html_title: "Zimbra Administration"" | jq -c '.[] | {ip: .ip, ports: [.services[].port]}'

![image](https://github.com/censys/censys-python/assets/108659226/91196556-bc93-490c-a4da-0ee176b28a81)

**Comment by thehappydinoa** [comment]
Hey there, it looks like you need to escape the quotes. Here is the same command with that included:

```sh
censys search "services.http.response.html_title: \"Zimbra Administration\"" | jq -c '.[] | {ip: .ip, ports: [.services[].port]}'
```
