### ISSUE TITLE
censys search only one port

### ISSUE THREAD

**Issue by lolminerxmrig** [censys/censys-python#506]
Hi.
me try code but need only one port no all port
censys search "services.http.response.html_title: \"WSO2 Management Console\"" | jq -c '.[] | {ip: .ip, ports: [.services[].port]}'

report :
{"ip":"95.217.153.182","ports":[22,443,9443]}
{"ip":"192.133.105.251","ports":[443]}
{"ip":"20.236.102.90","ports":[22,80,443,5601,5602,8001,8080,8200,8203,8243,8250,8251,8253,9093,9443,20001]}
{"ip":"35.166.241.167","ports":[21,22,443,445,446,8243,8280,9763,9765,9766]}
{"ip":"54.147.213.13","ports":[443]}
{"ip":"198.202.68.20","ports":[443,9443]}
{"ip":"44.230.199.131","ports":[80,443]}
{"ip":"140.143.170.124","ports":[22,80,123,3006,6379,8060,8080,8090,8302,9443]}
{"ip":"3.70.169.3","ports":[9444]}
{"ip":"3.84.70.103","ports":[443,9443]}
{"ip":"129.146.182.200","ports":[22,80,443,8443]}
{"ip":"137.141.14.75","ports":[443]}
{"ip":"186.217.0.72","ports":[22,3690,4041,7712,8010,8015,8020,9444,9712,14001]}
{"ip":"4.194.209.178","ports":[80,81,443,8243,9443,9444]}

I need example : 
http or https ://xxx.xxx.xxx.xxx:80 or 443

thanks

**Comment by thehappydinoa** [comment]
This little bash script should output what you are looking for:

```sh
#!/bin/bash

# Run the Censys search command and pipe the output to jq
censys_output=$(censys search "services.http.response.html_title: 'WSO2 Management Console'" | jq -c '.[] | {ip: .ip, ports: [.services[].port]}')

# Loop through each line of the output
while read -r line; do
  # Extract the IP address and ports from the line
  ip=$(echo "$line" | jq -r '.ip')
  ports=$(echo "$line" | jq -r '.ports[]')

  # Loop through each port and output the corresponding URL
  while read -r port; do
    if [ "$port" -eq 80 ]; then
      echo "http://$ip:$port"
    elif [ "$port" -eq 443 ]; then
      echo "https://$ip:$port"
    fi
  done <<< "$ports"
done <<< "$censys_output"
```

Output:

```plain
http://x.x.x.x:80
https://x.x.x.x:443
```

**Comment by lolminerxmrig** [comment]
can add save file to text.
thanks a lot.
