### ISSUE TITLE
CensysUnauthorizedException: 403 (Forbidden): Your user does not have permission to define specific fields.

### ISSUE THREAD

**Issue by cloudjunky** [censys/censys-python#524]
**Describe the bug**
If you execute `search_certs.py` you get the following error;

`censys.common.exceptions.CensysUnauthorizedException: 403 (Forbidden): Your user does not have permission to define specific fields.`

And as the 403 suggests if you strip out the fields the example works;

```"""Search certificate data set."""
from censys.search import CensysCerts

c = CensysCerts()


# Single page of search results
query = c.search(
    "parsed.subject.country: AU",
    sort=["parsed.issuer.organization", "parsed.subject.postal_code"],
)
hits = query()
print(hits)

# Multiple pages of search results
query = c.search(
    "parsed.subject.country: AU",
    sort=["parsed.issuer.organization", "parsed.subject.postal_code"],
    pages=2,
    per_page=5,
)
for hits in query:
    for hit in hits:
        print(hit)

# View all results
query = c.search(
    "parsed.subject.country: AU",
    sort=["parsed.issuer.organization", "parsed.subject.postal_code"],
    pages=2,
    per_page=5,
)
print(query.view_all())
```

**Comment by thehappydinoa** [comment]
Hi @cloudjunky 

At the moment only our paid accounts support defining fields. Please reach out to our sales team if you are interested in upgrading your account: [sales@censys.com](mail:sales@censys.com). For more information you can read [this support article](https://support.censys.io/hc/en-us/articles/360038755891-Purchasing-a-Censys-License).
