### ISSUE TITLE
Include cursor token in returned object for view_host_events() function

### ISSUE THREAD

**Issue by kylet-rf** [censys/censys-python#531]
The view_host_events() function [censys-python/censys/search/v2/hosts.py] returns a list of events, however this limits the user to a maximum 50 events because the cursor token isn't returned for follow on queries.

Request: Change the returned type to a dict and include the cursor token.

**Comment by thehappydinoa** [comment]
Hey @kylet-rf thanks for letting us know. This seems like an easy enough change, I will update this issue.

**Comment by thehappydinoa** [comment]
@kylet-rf I have updated this in 582d855863a751dfdb20e7ee4826c2ae8a42174d, I will update this issue when we cut a release.

**Comment by thehappydinoa** [comment]
Included in [Release v2.2.7](https://github.com/censys/censys-python/releases/tag/v2.2.7).
