### ISSUE TITLE
Switch from GET to POST results in 'name' key-value pair not being present for virtual host results

### ISSUE THREAD

**Issue by MaxGroot** [censys/censys-python#552]
**Describe the bug**

As of version `2.2.6`, the `.search()` method for CensysHosts does not return a `name` field anymore, which makes it impossible to know on which domain a result for a query has hit. Some troubleshooting suggests that this is caused by https://github.com/censys/censys-python/pull/541, as this switches the default HTTP Method for raw searches from `GET` to `POST`. If I patch line https://github.com/censys/censys-python/pull/541/files#diff-db8d97e8e7f157d85b660f239345ecab891f06073b952d732e5d81c3ef7dcc81R404 from `search_post_raw` to `search_get_raw`, I get the `name` field back in my results as expected. I don't know exactly why it was decided to switch from GET to POST or why the API does not return the `name` field for the `POST` requests that `censys-python` produces, but the end result is that the 'default' way of searching for virtual hosts is currently broken.

**To Reproduce**

```sh
pip install censys-python
python3
```

```python
from censys.search import CensysHosts
hosts = CensysHosts()
query = hosts.search('services.http.response.html_title="* My First Bug Report *"', per_page=100, pages=1, virtual_hosts="ONLY")
for page in query:
    for i in page:
        print(i["name"])
```

**Expected behavior**
* Like in previous versions, I expect the `name` key-value pair to be present for any query result so I can do a follow-up call to `.view()`.

**Device (please complete the following information):**
* OS: Ubuntu
* Censys version: 2.2.6

**Comment by thehappydinoa** [comment]
Hi @MaxGroot,

It should be working now, I just confirmed using this snipper that is has been correctly fixed.

```python
# Search for virtual hosts
query = h.search("not services.service_name: HTTP", per_page=5, virtual_hosts="ONLY")
for page in query:
    for host in page:
        print(host["name"])
```
