### ISSUE TITLE
Searching for hosts with fields is not supported in the CLI

### ISSUE THREAD

**Issue by martinmladenov** [censys/censys-python#558]
The `--fields` argument of the `search` CLI command is supported only when searching for certificates, even though the Censys API supports it for hosts as well.

This should be a pretty simple fix I think. The limitation only exists in the CLI client; the Python wrapper already supports this.

**Comment by thehappydinoa** [comment]
Hi there, fields is a supported argument, I think you may need to upgrade your censys client. Use this command to update: `pip install -U censys`.

**Comment by martinmladenov** [comment]
Hello @thehappydinoa,

Thank you for your answer, I indeed had an older version of the client.

I think it's worth noting that [the CLI documentation](https://censys-python.readthedocs.io/en/stable/usage-cli.html#search) is in this case outdated: "For the `certificates` index we can also add the --fields flag to specify which fields we want returned".

**Comment by thehappydinoa** [comment]
Thank you @martinmladenov I will update the tight away.
