### ISSUE TITLE
How to list the hosts of multiple software vendors at the same time in 1 search

### ISSUE THREAD

**Issue by sh3ll4rpw** [censys/censys-python#600]
**QUESTION 1**
I want to search for 3 different software vendors of a list of domains. Citrix, pabloaltonetworks and Sophos

When I search on "sarens.com" in the censys websearch I get a list of software vendors. When I use censys-python I don't have this list of software vendors in my results. It's possible to add software vendors to my output "censys search sarens.com" output? This would be the easiest. This can be done? If no please answer QUESTION2

**QUESTION2**
I know I can search for a single vendor like `censys search `"sarens.com and services.software.vendor: 'Citrix' "`

But when I search for multiple vendors like below. I get no output
```
"sarens.com and services.software.vendor: 'Fortinet' and services.software.vendor: 'Citrix' "
[]
```
How do I make the command above working so I can list the hosts of multiple software vendors in 1 search query.

**Comment by thehappydinoa** [comment]
Hey there, give this query a try:

```dsl
sarens.com and services.software.vendor: {'Fortinet', 'Citrix'}
```
