### ISSUE TITLE
plz help me fixed Error : 403 (Forbidden): Access was denied for this resource or feature.

### ISSUE THREAD

**Issue by lolminerxmrig** [censys/censys-python#640]
Hi.

plz help me fixed Error

403 (Forbidden): Access was denied for this resource or feature.

Code :
censys search 'services.http.response.html_title: ConnectWise ScreenConnect Remote Support Software' | jq -c '.[] | {ip: .ip, ports: [.services[].port]}'

![image](https://github.com/user-attachments/assets/f6c1631f-a326-4e2f-85ab-d0136fc77129)

**Comment by thehappydinoa** [comment]
Hey I think you need to put double quotes around the html title text.

**Comment by lolminerxmrig** [comment]
plz add sample.

**Comment by ISaIGoI** [comment]
You have limited API access for 60 days and must pay for an upgrade to use it more!
![Screenshot 2024-10-14 120940](https://github.com/user-attachments/assets/52f78fe4-7abd-49a6-ad81-d32e5b308d8e)

**Comment by thehappydinoa** [comment]
@lolminerxmrig try this
```sh
censys search 'services.http.response.html_title: "ConnectWise ScreenConnect Remote Support Software"'
```

**Comment by lolminerxmrig** [comment]
> @lolminerxmrig try this
> 
> ```shell
> censys search 'services.http.response.html_title: "ConnectWise ScreenConnect Remote Support Software"'
> ```

not working.

**Comment by thehappydinoa** [comment]
Can you elaborate on what is not working?

**Comment by ISaIGoI** [comment]
> > @lolminerxmrig try this
> > ```shell
> > censys search 'services.http.response.html_title: "ConnectWise ScreenConnect Remote Support Software"'
> > ```
> 
> not working.

I had the same issue, but I created a new FREE account and changed API ID&SECRET to the new account, now works fine!

**Comment by lolminerxmrig** [comment]
yes my account old.

**Comment by ISaIGoI** [comment]
> yes my account old.

Make a new account, then go to this path" ~/.config/censys/" and change "api_id api_secret" on "censys.cfg"file with nano or vim text editor.
![WindowsTerminal_Vjbj0PTaFn](https://github.com/user-attachments/assets/546b4587-8ee2-44f4-aff4-8bd6548f57af)

**Comment by thehappydinoa** [comment]
Hi there, please note that this type of multi-account usage is against our terms of service and I will be locking this issue.
