### ISSUE TITLE
ImportError: No module named certificates

### ISSUE THREAD

**Issue by blueteamzone** [censys/censys-python#85]
Hi, we are getting No module named certificates when using this lib.
Our script is currently running on an ubuntu box with python `Python 3.8.0`.
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

**To Reproduce**
1. python3 -m venv .venv
2. source .venv/bin/activate
3. python
4. import censys.certificates <-- Error ModuleNotFoundError: No module named 'censys.certificates'

pip show censys
```
Name: censys
Version: 2.0.0
Summary: An easy-to-use and lightweight API wrapper for Censys APIs (censys.io).
Home-page: UNKNOWN
Author: Censys Team
Author-email: support@censys.io
License: Apache License, Version 2.0
Location: /home/tony/expanse/.venv/lib/python3.8/site-packages
Requires: requests, backoff
Required-by:
```
We also check previous issues related to import errors.
Our python script is called `censys_subdomain.py` and we also removed pyc files as suggested [here ](https://github.com/censys/censys-python/issues/25#issuecomment-459157847)
We are following the guide provided in your docs at https://censys.io/api.
![image](https://user-images.githubusercontent.com/60802334/118102876-99877a80-b3d9-11eb-832b-4e5f7fc64e37.png)

**Comment by thehappydinoa** [comment]
Hi @blueteamzone we are working on updating our docs on the new search site search.censys.io. In the mean time the most up to date documentation can be found on [ReadTheDocs](https://censys-python.readthedocs.io/en/stable/usage-v1.html#view). I have linked to an example import statement. Many of the pats have changed as we have upgraded to a namespace package for more advanced functionality. If you have any more questions please feel free to reach out or create a discussion post.

**Comment by thehappydinoa** [comment]
Hi @blueteamzone I just updated the examples on our site. For more examples you can also see our [examples](https://github.com/censys/censys-python/tree/main/examples). For now I am going to close this issue.
