### ISSUE TITLE
Publish an update as 0.0.6

### ISSUE THREAD

**Issue by konklone** [Censys/censys-python#9]
To use the censys library with its current (helpful) API, where a `page` parameter can be sent in to the main search method, I need to clone the repo and run `python setup.py install` rather than `pip install`. A version hasn't been published since April, so a `0.0.6` (which still doesn't imply any stability or backwards compatibility) would be helpful.

**Comment by zakird** [comment]
I have uploaded 0.0.6 which includes everything in the current master.
