### ISSUE TITLE
Support for `Fields` in bulk method 

### ISSUE THREAD

**Issue by r0ny123** [censys/censys-python#93]
**Is your feature request related to a problem? Please describe.**
Let's say we have some `certficates`/`IPs` specific to an `threat actor`, now we want to know to what is/are common(s) to those `certificates`/`IPs`, so we can pivot based on that specific fields' values, and build a query to search for other similar `certificates`/`IPs`. It will be very helpful for quick pivoting and infrastructure hunting.

**Describe the solution you'd like**
I wan to get the specific fields' value while querying the `certificates`/`IPs`(if it ever gets support for that), in bulk to pivot further, based on returned field results.

**Additional context**
Currently, the bulk method is only available for `CensysCertificates` index as stated [here](https://censys-python.readthedocs.io/en/stable/usage-v1.html#bulk), do you have any plan to include to it for `CensysIPv4`/`CensysHosts`?

**Comment by thehappydinoa** [comment]
Hi there, in terms of adding the `bulk` method to IPv4 and Hosts I believe that is not on the roadmap. However, I am planning on implementing a `view_all` method to the v2 indexes (`CensysHosts`). The ticket for this is #95 if you want to follow along with its progress.

**Comment by r0ny123** [comment]
Hello thanks for the reply. But can we guys consider having it on your roadmap? That will be really helpful for analysts/researchers.

**Comment by thehappydinoa** [comment]
Ah I see what you were getting at, I will create a ticket for it and reopen this issue.

**Comment by thehappydinoa** [comment]
Hi @r0ny123, after reviewing this issue I have determined it is outside of the scope for this project. For now I am going to close this issue, however if you would like to file an official feature request, I would ask that you contact support@censys.io. 
Thank you for your feedback.
